### ISSUE TITLE
Valore errato nella colonna lat

### ISSUE THREAD

**Issue by aborruso** [emergenzeHack/covid19italia_data#1]
In corrispondenza della issue https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/120 c'è un valore di cella pari a `43.4861359,`.

Faccio riferimento al [CSV sulle issue](https://github.com/emergenzeHack/covid19italia_data/blob/eafae53992188db8895d582de7ce3698f3926649/issues.csv).

La virgola alla fine non dovrebbe esserci

**Comment by avivace** [comment]
Sistemato! Grazie!
